Hunter task
matthewkeil/vue-flash-cards pull request #2
Opened 2022-09-03 21:39 UTC by Hunta88

`verbTense` objects inside of functions `buildPast`, `buildPresent`, `buildPast`,and  `buildConditional` were populated with props  `continuous`, `simple`, `perfect`, and `perfectContinuous` 

```
hunter@hunter-lenovo:~/Documents/GitHub_Repos/vue-flash-cards/packages/utils$ npm run ts src/main

> @spanish-english-flash-cards/utils@1.0.0 ts
> node -r ts-node/register "src/main"

{
  root: 'move',
  infinitive: 'to move',
  presentParticiple: 'moveing',
  pastSimple: 'moved',
  pastParticiple: 'moved',
  past: {
    continuous: {
      I: 'was moved',
      you: 'were moved',
      it: 'was moved',
      we: 'were moved',
      youAll: 'were moved',
      they: 'were moved'
    },
    simple: {
      I: 'moved',
      you: 'moved',
      it: 'moved',
      we: 'moved',
      youAll: 'moved',
      they: 'moved'
    },
    perfect: {
      I: 'had moved',
      you: 'had moved',
      it: 'had moved',
      we: 'had moved',
      youAll: 'had moved',
      they: 'had moved'
    },
    perfectContinuous: {
      I: 'had been moveing',
      you: 'had been moveing',
      it: 'had been moveing',
      we: 'had been moveing',
      youAll: 'had been moveing',
      they: 'had been moveing'
    }
  },
  present: {
    continuous: {
      I: 'am moveing',
      you: 'are moveing',
      it: 'is moveing',
      we: 'are moveing',
      youAll: 'are moveing',
      they: 'are moveing'
    },
    simple: {
      I: 'move',
      you: 'move',
      it: 'moves',
      we: 'move',
      youAll: 'move',
      they: 'move'
    },
    perfect: {
      I: 'have moved',
      you: 'have moved',
      it: 'has moved',
      we: 'have moved',
      youAll: 'have moved',
      they: 'have moved'
    },
    perfectContinuous: {
      I: 'have been moveing',
      you: 'have been moveing',
      it: 'has been moveing',
      we: 'have been moveing',
      youAll: 'have been moveing',
      they: 'have been moveing'
    }
  },
  future: {
    continuous: {
      I: 'will be moveing',
      you: 'will be moveing',
      it: 'will be moveing',
      we: 'will be moveing',
      youAll: 'will be moveing',
      they: 'will be moveing'
    },
    simple: {
      I: 'will move',
      you: 'will move',
      it: 'will move',
      we: 'will move',
      youAll: 'will move',
      they: 'will move'
    },
    perfect: {
      I: 'will have moved',
      you: 'will have moved',
      it: 'will have moved',
      we: 'will have moved',
      youAll: 'will have moved',
      they: 'will have moved'
    },
    perfectContinuous: {
      I: 'will have been moveing',
      you: 'will have been moveing',
      it: 'will have been moveing',
      we: 'will have been moveing',
      youAll: 'will have been moveing',
      they: 'will have been moveing'
    }
  },
  conditional: {
    present: {
      I: 'would move',
      you: 'would move',
      it: 'would move',
      we: 'would move',
      youAll: 'would move',
      they: 'would move'
    },
    presentContinuous: {
      I: 'would be moveing',
      you: 'would be moveing',
      it: 'would be moveing',
      we: 'would be moveing',
      youAll: 'would be moveing',
      they: 'would be moveing'
    },
    past: {
      I: 'would have moved',
      you: 'would have moved',
      it: 'would have moved',
      we: 'would have moved',
      youAll: 'would have moved',
      they: 'would have moved'
    },
    pastContinuous: {
      I: 'would have been moveing',
      you: 'would have been moveing',
      it: 'would have been moveing',
      we: 'would have been moveing',
      youAll: 'would have been moveing',
      they: 'would have been moveing'
    }
  }
}
```

2022-09-03 22:53 UTC, matthewkeil requested changes
great work and thanks for tackling this bug!!

2022-09-03 22:53 UTC, matthewkeil commented on packages/utils/src/englishConjugation/conjugateEnglish.ts
> +    }
awesome job with this.  default initialization was definitely the error and you hit the nail on the head!

The loop below on L#67-L#73 will take care of building the actual values for us.  How do you feel about going with the suggestion below?

```suggestion
    simple: {},
    perfect: {},
    perfectContinuous: {}
```

2022-09-03 22:53 UTC, matthewkeil commented on packages/utils/src/englishConjugation/conjugateEnglish.ts
> +    }
Good catch with the initialization!!

Similar to the above.  Lets let the loop do the repetitious part for us

```suggestion
    continuous: {},
    simple: {},
    perfect: {},
    perfectContinuous: {}
```

2022-09-03 22:53 UTC, matthewkeil commented on packages/utils/src/englishConjugation/conjugateEnglish.ts
> +  } as EnglishVerbTense;
```suggestion
    continuous: {},
    simple: {},
    perfect: {},
    perfectContinuous: {}
  } as EnglishVerbTense;
```

2022-09-03 22:53 UTC, matthewkeil commented on packages/utils/src/englishConjugation/conjugateEnglish.ts
> +  } as EnglishConditionalTense
spectacular job!!!

2022-09-04 16:11 UTC, Hunta88 commented
commited the three suggestions. 

main.ts still run same as before. So all good.

```
Hunter Desktop@DESKTOP-DH6UJ86 MINGW64 ~/Documents/GitHub/vue-flash-cards/packages/utils (hunter-task)
$ npm run ts src/main

> @spanish-english-flash-cards/utils@1.0.0 ts
> node -r ts-node/register "src/main"

{
  root: 'move',
  infinitive: 'to move',
  presentParticiple: 'moveing',
  pastSimple: 'moved',
  pastParticiple: 'moved',
  past: {
    continuous: {
      I: 'was moved',
      you: 'were moved',
      it: 'was moved',
      we: 'were moved',
      youAll: 'were moved',
      they: 'were moved'
    },
    simple: {
      I: 'moved',
      you: 'moved',
      it: 'moved',
      we: 'moved',
      youAll: 'moved',
      they: 'moved'
    },
    perfect: {
      I: 'had moved',
      you: 'had moved',
      it: 'had moved',
      we: 'had moved',
      youAll: 'had moved',
      they: 'had moved'
    },
    perfectContinuous: {
      I: 'had been moveing',
      you: 'had been moveing',
      it: 'had been moveing',
      we: 'had been moveing',
      youAll: 'had been moveing',
      they: 'had been moveing'
    }
  },
  present: {
    continuous: {
      I: 'am moveing',
      you: 'are moveing',
      it: 'is moveing',
      we: 'are moveing',
      youAll: 'are moveing',
      they: 'are moveing'
    },
    simple: {
      I: 'move',
      you: 'move',
      it: 'moves',
      we: 'move',
      youAll: 'move',
      they: 'move'
    },
    perfect: {
      I: 'have moved',
      you: 'have moved',
      it: 'has moved',
      we: 'have moved',
      youAll: 'have moved',
      they: 'have moved'
    },
    perfectContinuous: {
      I: 'have been moveing',
      you: 'have been moveing',
      it: 'has been moveing',
      we: 'have been moveing',
      youAll: 'have been moveing',
      they: 'have been moveing'
    }
  },
  future: {
    continuous: {
      I: 'will be moveing',
      you: 'will be moveing',
      it: 'will be moveing',
      we: 'will be moveing',
      youAll: 'will be moveing',
      they: 'will be moveing'
    },
    simple: {
      I: 'will move',
      you: 'will move',
      it: 'will move',
      we: 'will move',
      youAll: 'will move',
      they: 'will move'
    },
    perfect: {
      I: 'will have moved',
      you: 'will have moved',
      it: 'will have moved',
      we: 'will have moved',
      youAll: 'will have moved',
      they: 'will have moved'
    },
    perfectContinuous: {
      I: 'will have been moveing',
      you: 'will have been moveing',
      it: 'will have been moveing',
      we: 'will have been moveing',
      youAll: 'will have been moveing',
      they: 'will have been moveing'
    }
  },
  conditional: {
    present: {
      I: 'would move',
      you: 'would move',
      it: 'would move',
      we: 'would move',
      youAll: 'would move',
      they: 'would move'
    },
    presentContinuous: {
      I: 'would be moveing',
      you: 'would be moveing',
      it: 'would be moveing',
      we: 'would be moveing',
      youAll: 'would be moveing',
      they: 'would be moveing'
    },
    past: {
      I: 'would have moved',
      you: 'would have moved',
      it: 'would have moved',
      we: 'would have moved',
      youAll: 'would have moved',
      they: 'would have moved'
    },
    pastContinuous: {
      I: 'would have been moveing',
      you: 'would have been moveing',
      it: 'would have been moveing',
      we: 'would have been moveing',
      youAll: 'would have been moveing',
      they: 'would have been moveing'
    }
  }
}
```

2022-09-04 20:04 UTC, matthewkeil commented
@Hunta88 excellent work!  Good job re-pulling and making sure it still worked!  That is a big step actually because often times the suggestions are close but may not be perfectly syntactically correct.  You aced this one!

2022-09-04 20:05 UTC, merged